trigger: none 
name: resources create with dependency
pool: infra_pool
jobs:
- job: terraforminstall 
  displayName: job-1 terraform install
  steps: 
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'

  - task: TerraformTask@5
    displayName: terraform init
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/'
      backendServiceArm: 'brij'
      backendAzureRmResourceGroupName: 'rg_infra'
      backendAzureRmStorageAccountName: 'storageinfra'
      backendAzureRmContainerName: 'contenerinfra'
      backendAzureRmKey: 'brij.tfstate'

  - task: TerraformTask@5
    displayName: terraform plan
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/'
      environmentServiceNameAzureRM: 'brij'

  
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'destroy'
      workingDirectory: '$(System.DefaultWorkingDirectory)/'
      commandOptions: '-auto-approve'
      environmentServiceNameAzureRM: 'brij'




